[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "2.7.0"
rand = "0.8.5"
rand_core = "0.6.4"
rand_xorshift = "0.3.0"
